### ISSUE TITLE
not an issue, an idea

### ISSUE THREAD

**Issue by bggangel** [arsi-apli/UltraRemote#4]
Not sure how I can put requests or improvement ideas in GitHub, but here is one:
Would it be possible to delete the files from the printer? Right now, you have to use the touch screen, and that is clumsy/slow.
If you could have an 'explorer-like' view of the files on the printer and the ability to delete some. 
Does the API support that?

**Comment by arsi-apli** [comment]
Not currently, all I found was reverse engineering of Chitubox communication with the printer and it doesn't know that.
But I'm currently working on patching the firmware and if it succeeds, I'll be able to connect windows share and I'm strongly considering to do a make my own printing app (firmware side), because that one is a tragedy.. It runs on linux and it knows basically nothing, making a proper web interface would probably kill them..
https://github.com/arsi-apli/UltraFirmwareToolkit

**Comment by bggangel** [comment]
Very interesting. I will keep my eye on that.
