### ISSUE TITLE
Connects but won't send file.

### ISSUE THREAD

**Issue by ChrisRArendt** [arsi-apli/UltraRemote#5]
<img width="533" alt="image" src="https://github.com/arsi-apli/UltraRemote/assets/994787/eaf798df-e517-4b3c-8775-32f78291fe84">
Progress is 0 for a long time.

**Comment by ChrisRArendt** [comment]
can see the progress tho
<img width="532" alt="image" src="https://github.com/arsi-apli/UltraRemote/assets/994787/9c7a0890-3138-4d3b-9928-0beb87085d30">

**Comment by arsi-apli** [comment]
Please try renaming the file to test.goo and see if it works.
If it helped, I'll have to make an algorithm that modifies the filename..
If that doesn't work, leave the ultraremote running and type` http://localhost:port/test.go`o into your web browser. 
Instead of port, enter the number shown here:
![image](https://github.com/arsi-apli/UltraRemote/assets/22594510/fedd938f-0327-4628-b68a-8d287a513be6)
Attention, every time you run UltraRemote, the number will change..
If the file doesn't start downloading, there's a problem with your firewall or with the file's access rights. If it works, we have to look further for the cause..
btw:
![image](https://github.com/arsi-apli/UltraRemote/assets/22594510/c3adab0a-4f36-4adc-9bc5-3d6a23444027)

**Comment by ChrisRArendt** [comment]
Renaming to test.goo works, and, now, you works to make it work with other filenames :D

**Comment by arsi-apli** [comment]
I made a new version, but my printer is at the cottage, so I don't have a way to test it...
Please test it and let me know if it works  and I'll make a commit and a new version. Thank you. 
http://server.arsi.sk/UltraRemote-01.00-shaded.jar

**Comment by ChrisRArendt** [comment]
Thank you, but it doesn't work. Had to go back to the other version and name my file test.goo and rename it after transferring.

**Comment by arsi-apli** [comment]
I'll fine-tune it on Friday..
If it replaced all unauthorized characters in the filename with "_". So there may be a problem with the length of the filename.

**Comment by arsi-apli** [comment]
I'll try using the current time in milliseconds as the filename for the download and the original filename in the header as the filename.

**Comment by ChrisRArendt** [comment]
Any progress? :)

**Comment by Jinxd10r** [comment]
I'm having this same issue  . I can connect fine , and see all printer info and activity, but cannot send to printer, just sits on waiting for the file transfer to complete. I have tried all mentioned above as well as disabling my firewall . localhost returns a 404 . using current release ,Chitubox send files without issue. Running 1.5.0 firmware. Any help would be greatly appreciated!
